### ISSUE TITLE
Handler for script_raised_built event

### ISSUE THREAD

**Issue by robot256** [ForsakenShell/LogisticsWagons#3]
The event handler for `script_raised_built` should access `event.entity` instead of `event.created_entity`.  

See the API documentation here:  https://lua-api.factorio.com/0.17.79/events.html#script_raised_built

The easiest way to do this would be to make control.lua:23 `local entity = event.created_entity or event.entity`.  If `event.created_entity` is null (does not exist), it will pick `event.entity` instead.

**Comment by ForsakenShell** [comment]
Thanks for the heads up, fix implemented in the repo.
